# Generated by Django 4.2.6 on 2023-11-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название привычки')),
                ('action', models.CharField(max_length=100, verbose_name='действие')),
                ('time_begin', models.DateTimeField(blank=True, null=True, verbose_name='время начала привычки')),
                ('place', models.CharField(max_length=30, verbose_name='место')),
                ('is_pleasant_habit', models.BooleanField(blank=True, default=False, null=True, verbose_name='признак_приятной_привычки')),
                ('time_period', models.DurationField(blank=True, null=True, verbose_name='периодичность привычки')),
                ('award', models.CharField(blank=True, max_length=30, null=True, verbose_name='вознаграждение')),
                ('time_limit', models.DurationField(blank=True, null=True, verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(blank=True, default=False, null=True, verbose_name='признак_публичности')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
