# Generated by Django 4.2.6 on 2023-11-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_limit',
            field=models.TimeField(blank=True, null=True, verbose_name='время на выполнение'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time_period',
            field=models.TimeField(blank=True, null=True, verbose_name='периодичность привычки'),
        ),
    ]
