# Generated by Django 4.2.6 on 2023-11-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_time_limit_alter_habit_time_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='time_limit',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='time_period',
        ),
        migrations.AddField(
            model_name='habit',
            name='time_limit_seconds',
            field=models.IntegerField(blank=True, null=True, verbose_name='время на выполнение'),
        ),
        migrations.AddField(
            model_name='habit',
            name='time_period_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='периодичность привычки'),
        ),
    ]
